### ISSUE TITLE
Dear Darin M223. I try to download and run lein figwheel but I got error and the program doesn't run. 

### ISSUE THREAD

**Issue by ThinhPTran** [DarinM223/spreadsheet#1]

**Comment by DarinM223** [comment]
Can you provide the error?

**Comment by ThinhPTran** [comment]
Dear DarinM223
Figwheel: Starting server at http://localhost:3449
Figwheel: Watching build - app
Compiling "target/cljsbuild/public/js/app.js" from ("src/cljs" "src/cljc" "env/dev/cljs")...
nil
java.io.FileNotFoundException: env/dev/cljs (Datei oder Verzeichnis nicht gefunden)

It seems that it is looking for env/dev/cljs as specified in project.clj but it doesn' find it. 

Best regards, 
Thinh P. Tran

**Comment by DarinM223** [comment]
I think that my global gitignore file prevented the env directory from being committed. I committed the env directory, and now I can clone the repository into a new folder and run the project without errors, so the problem should be fixed now. Thanks for reporting this issue!

**Comment by ThinhPTran** [comment]
It works. I am playing with it now.
